tp2/webapp/webapp/forms.py
from flask.ext.wtf import Form
from wtforms.fields import HiddenField, FieldList


class SugestoesForm(Form):
    """Formulário responsável por transmitir os dados dos filmes visua-
    lizados pelo usuário.
    """
    assistidos = HiddenField()

tp2/webapp/webapp/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
import os

def create_app(Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    Bootstrap(app)

    from webapp.db import mongo
    mongo.init_app(app)

    from webapp.views import views
    app.register_blueprint(views)

    if not os.path.exists(app.config['POSTERS_END']):
        os.makedirs(app.config['POSTERS_END'])

    return app

tp2/webapp/webapp/views.py
from flask import render_template, request, redirect, current_app, Blueprint
from webapp import forms
from webapp.sugestoes import engine, parser
import json

views = Blueprint('views', __name__)

@views.route('/')
def index():
    """Página principal do site."""
    return render_template("home.html")

@views.route('/sobre')
def sobre():
    """Sobre o trabalho."""
    return render_template("sobre.html")

@views.route('/form')
def form():
    """Formulário de seleção de filmes assistidos."""
    formulario = forms.SugestoesForm()
    dados = parser.obter_lista_filmes(
        engine.mais_populares(current_app.config['NUM_ASSISTIDOS']))

    return render_template("form.html", dados=dados, form=formulario)


@views.route('/sugestoes', methods=['POST', 'GET'])
def resultados():
    """Página de resultados, acessível apenas pelo formulário form().
    """
    formulario = forms.SugestoesForm()

    if formulario.validate_on_submit():
        # Obtém movie_ids inteiros do JSON fornecido pelo campo hidden
        movie_ids = [int(x) for x in json.loads(formulario.assistidos.data)]
        imdb_ids = engine.sugestoes(movie_ids, current_app.config['NUM_SUGESTOES'])
        dados = parser.obter_lista_filmes(imdb_ids)
        return render_template("sugestoes.html", dados=dados)

    return redirect('/form')

tp2/webapp/webapp/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Teste{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}"/>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Mobile nav (com botão de toggle) -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TP2d</a>
    </div>

    <!-- Itens da navegação -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('views.index') }}">Home</a></li>
        <li><a href="{{ url_for('views.form') }}">Sugestões</a></li>
        <li><a href="{{ url_for('views.sobre') }}">Sobre</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
  
  {% block container %}

  <p>Funciona, I guess.</p>

  {% endblock %}
</div>
<footer class="footer">
  <div class="container">
    {% block footer %}
      <p>Feito por Victor Diniz.</p>
      <p>Esse site utiliza orgulhosamente <a href="http://flask.pocoo.org/">Flask</a>, <a href="http://www.mongodb.org/">MongoDB</a> e <a href="http://getbootstrap.com/">Bootstrap</a> (com o tema <a href="http://bootswatch.com/sandstone/">Sandstone</a>, do Bootswatch)</p>
    {% endblock %}
  </div>
</footer>
{% endblock %}

tp2/webapp/webapp/templates/form.html
{% extends "base.html" %}

{% block title %}Sugestões{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='form.js') }}"></script>
{% endblock %}

{% block container %}
<div class="row">
    <!-- Coluna da esquerda: flavour text -->
    <div class="col-md-4 col-lg-3">
        <h1>Conte-nos sobre seu gosto</h1>
        <p>Marque os filmes que você já assistiu (pelo menos um é necessário) da seleção de filmes mais populares e obtenha recomendações personalizadas para a sua próxima tarde de frio, cobertores e pipoca quentinha.</p>
    </div>
    <!-- Coluna da direita: filmes -->
    <div class="col-md-8 col-lg-9">
        <div class="row">
        {% for filme in dados %}
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
                <!-- Pôster do filme com tooltip com nome e ano -->
                <a href="javascript:void(0)" class="thumbnail filme" title="{{ filme[1]['Title'] }} ({{ filme[1]['Year'] }})" data-toggle="tooltip" data-placement="bottom">
                    <img src="{{ filme[2] }}" alt="Poster" class="poster formulario" draggable="false">
                    <span class="movie_id" hidden>{{ filme[0] }}</span>
                </a>
            </div>
        {% endfor %}
        </div>
        <form action="/sugestoes" method="post" name="sugestoes">
            {{ form.assistidos }}
            <button id="form-submit" type="submit" class="btn btn-success" disabled>Enviar</button>
        </form>
    </div>
</div> <!-- div.row -->
{% endblock %}

tp2/webapp/webapp/templates/home.html
{% extends "base.html" %}

{% block title %}TP2d - Sistema de Recomendações{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='home.js') }}"></script>
{% endblock %}

{% block container %}
<h1>TP2d - Sistema de recomendações</h1>
<p>Trabalho prático de Algoritmos e Estruturas de Dados II na Universidade Federal de Minas Gerais.</p>

<img src="{{ url_for('static', filename='movies.jpg') }}" alt="" class="img-responsive">
<div class="row">
    <div class="col-md-6">
        <h2>Obtenha recomendações</h2>
        <p>Descubra quais vão ser os filmes da sua próxima tarde de cinema! Acesse o sistema de recomendações pelo link abaixo, preencha quais filmes você já assistiu e receba sugestões inteligentes juntamente com links para que você possa saber mais sobre cada filme.</p>
        <a href="{{ url_for('views.form') }}" class="btn btn-primary btn-lg"><i class="fa fa-check-square-o"></i> Formulário</a>
    </div>
    <div class="col-md-6">
        <h2>Saiba mais</h2>
        <p>Descubra como funciona o programa, saiba como instalá-lo localmente para testes e desenvolvimento e obtenha acesso ao código fonte (a partir de 03/12/2014).</p>
        <a href="{{ url_for('views.sobre') }}" class="btn btn-primary">Sobre o trabalho</a> <a class="btn btn-default" href="https://github.com/blekwave/AEDS2/tree/master/tp2"><i class="fa fa-github"></i> Github</a>
    </div>
</div>
{% endblock %}

tp2/webapp/webapp/templates/sobre.html
{% extends "base.html" %}

{% block title %}Sobre o trabalho{% endblock %}

{% block container %}
<h1>Sobre o trabalho</h1>

<h2>A proposta</h2>
<p>Esse site foi feito como desafio extra de um trabalho prático da disciplina de AEDS II, na <a href="http://ufmg.br">UFMG</a>. O trabalho original envolvia, em C, fazer um sistema de recomendações de filmes que operasse no terminal e lesse sua entrada de um arquivo de texto. Seu enunciado está disponível <a href="{{ url_for('static', filename='enunciado.pdf') }}">neste link</a>. A minha implementação não está disponível nesse site, já que esse trabalho ainda está aberto. A documentação do meu trabalho, no entanto, <a href="{{ url_for('static', filename='doc.pdf') }}">pode ser acessada</a>, e ela descreve detalhadamente a implementação dele e as escolhas tomadas.</p>
<p>A proposta do desafio era fazer uma interface web para o sistema de sugestões, em que o usuário poderia preencher um formulário com seus filmes assistidos e obter sugestões, de acordo com as bases de dados e o sistema implementado previamente. Este site é a minha implementação desse desafio, feito em Python 3 com o framework web <a href="http://flask.pocoo.org/">Flask</a>. A escolha de Flask foi feita pela facilidade de implementar um sistema novo de forma elegante e livre de gambiarras, já que esse framework é muito flexível e dá bastante liberdade ao desenvolvedor nas suas escolhas. Além disso, Python 3 tem a vantagem de ter suporte direto a Unicode, o que retira do desenvolvedor a necessidade de lidar com esse tipo de problema ou realizar algum tipo de encoding nos templates HTML.</p>

<h2>Integração</h2>
<p>O primeiro desafio envolvido neste trabalho foi integrar Python e C, já que reimplementar todo o sistema de sugestões me pareceu uma forma muito ineficiente de realizar o que foi proposto. Por isso, foram feitos, com base nas bibliotecas utilizadas no trabalho principal, programas principais alternativos, que recebiam a entrada como parâmetro na linha de comando. Esses programas são invocados como subprocessos e realizam a geração das sugestões. Por isso, ao sistema em Python, só resta, tendo em mãos os identificadores de cada filme no IMDb, obter os dados sobre cada filme e gerenciar a interação com o usuário. Inicialmente, foi considerada a possibilidade de utilizar o sistema de extensão de Python com bibliotecas em C, mas a ideia foi rapidamente descartada por ser um sistema bem mais complexo do que o necessário.</p>

<h2>Obtenção de dados dos filmes</h2>
<p>Para obter as informações sobre cada filme a partir do imdbID de cada lançamento, foi utilizada a <a href="http://www.omdbapi.com/">OMDb API</a>. Essa API retorna um objeto JSON que contém todos os dados necessários para o site. O uso da API torna desnecessário tentar obter esses dados manualmente do site do IMDb, o que seria mais propenso a erros e difícil de implementar. A disposição dos dados é feita através do sistema de templates utilizado em Flask, Jinja2, utilizando a extensão <a href="http://pythonhosted.org/Flask-Bootstrap/">Flask-Bootstrap</a> para criar uma interface agradável e responsiva sem grande dificuldade.</p>
<p>Efetuar tantos pedidos à API é muito lento, porém. Isso causava grande lentidão na geração das sugestões e tomava bem mais tempo do que gerar as sugestões em si. Para remediar esse problema, foi implementado um sistema de cache dos dados de cada filme em um banco de dados MongoDB. Com isso, só é preciso realizar o pedido à API uma vez. Como os filmes mais populares exibidos no formulário são sempre os mesmos, o desempenho da página do formulário teve grande melhora quando esse cache foi originalmente implementado.</p>

<h2>Outras características</h2>
<p>Prestar um serviço de qualidade é sempre uma boa meta. Para isso, o sistema não só diz ao usuário quais filmes ele recomenda, mas também revela várias informações relevantes de forma visualmente agradável. A página de sugestões mostra a duração do filme, o seu gênero, o diretor, as avaliações do filme no IMDb e no Metacritic (metascore) e também disponibiliza um botão para mostrar a sinopse do filme em um pop-up. Para facilitar a visualização, as notas de cada filme são coloridas diferentemente de acordo com o valor. Isso é feito através de algumas funções em Javascript, utilizando jQuery para programar de forma compacta e eficiente.</p>
<p>Do lado de cada filme, é mostrado seu pôster. No entanto, isso se mostrou um desafio quando o programa foi exportado para este servidor, já que o IMDb tem um sistema de proteção contra hotlinking de suas imagens. Por isso, também foi necessário implementar um cache dos pôsteres de cada filme. Se o filme não teve sua imagem salva ainda no cache, o sistema envia um pedido e baixa esse pôster, de forma a não causar problemas ou gerar um erro de acesso proibido. Isso também traz o benefício de realizar menos acessos a servidores remotos.</p>

<div class="row">
    <div class="col-md-6">
        <h2>Instalação</h2>
        <p>É necessário ter, além dos arquivos desse website, o código fonte ou executáveis dos programas auxiliares para gerar as sugestões, CMake, um compilador C (preferivelmente GCC, o único testado), Python 3, Virtualenv e uma instalação de MongoDB na máquina.</p>
        <ol>
            <li>Compile os programas auxiliares usando o CMake.</li>
            <li>Copie os programas <em>Populares</em> e <em>Individual</em> para a pasta <em>geradores</em>, dentro da pasta do website.</li>
            <li>Crie um ambiente virtual com <em>virtualenv</em> onde achar conveniente (e ative esse ambiente).</li>
            <li>
                Baixe as dependências do website através do arquivo <em>requirements.txt</em> com Pip:
                <code>pip install -r requirements.txt</code>
            </li>
            <li>Edite os arquivos de configuração de acordo com os dados do servidor.</li>
            <li>Execute diretamente o arquivo principal <em>run.py</em> ou utilize um servidor WSGI auxiliar.</li>
            <li>Opcional: configure um <em>reverse proxy server</em> (Nginx, Apache) para gerenciar o acesso ao website.</li>
        </ol>
    </div>
    <div class="col-md-6">
        <h2>Sobre o autor</h2>
        <div class="media">
            <div class="media-left">
                <img src="{{ url_for('static', filename='eu.jpg') }}" height="150px" width="150px" alt="" class="img-circle">
            </div>
            <div class="media-body">
                <h4 class="media-heading">Victor Pires Diniz</h3>
                <p>Aluno no segundo período do curso de Ciência da Computação da UFMG. Gosta de fightans, platformers, programação e música de qualidade discutível. Ainda não faz ideia de qual é a dessa vida maluca, mas até o momento vem gostando muito dela.</p>
            </div>
        </div>
    </div>
</div>



{% endblock %}

tp2/webapp/webapp/templates/sugestoes.html
{% extends "base.html" %}

{% block title %}Sugestões{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='sugestoes.js') }}"></script>
{% endblock %}

{% block container %}
<h1>Suas recomendações</h1>
<p>Nosso sistema processou os seus filmes assistidos e concluiu que você pode gostar dos filmes a seguir:</p>
<div class="row">
{% for filme in dados %}
    <div class="col-lg-4 col-md-6 col-xs-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="media">
                    <a class="media-left" href="http://www.imdb.com/title/{{ filme[1]['imdbID'] }}">
                        <img src="{{ filme[2] }}" alt="Poster" class="poster resultados" draggable="false">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{ filme[1]['Title'] }} ({{ filme[1]['Year'] }})</h4>
                        <p>{{ filme[1]['Runtime'] }} | {{ filme[1]['Genre'] }}</p>
                        <p><strong>Diretor: </strong>{{ filme[1]['Director'] }}</p>
                        <div class="button-drawer">
                            <button type="button" class="btn btn-primary" data-container="body" data-toggle="popover" title="Sinopse" data-content="{{ filme[1]['Plot'] }}" data-placement="bottom"><i class="fa fa-book fa-lg"></i></button>
                            <a class="btn imdb_rating" target="_blank" href="http://www.imdb.com/title/{{ filme[1]['imdbID'] }}" title="IMDb" data-toggle="tooltip" data-placement="bottom" data-container="body">{{ filme[1]['imdbRating'] }}</a>
                            <a class="btn metacritic_rating" target="_blank" href="http://www.metacritic.com/search/movie/{{ filme[1]['Title'] }}/results" title="Metascore" data-toggle="tooltip" data-placement="bottom" data-container="body">{{ filme[1]['Metascore'] }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}